# Generated by Django 5.1 on 2024-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_nutrition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("elite", "Elite"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_months", models.IntegerField()),
            ],
        ),
    ]
